### ISSUE TITLE
Problem with Patch #7444

### ISSUE THREAD

**Issue by h3ndro** [Eyepea/redmine_auto_assigned_user#2] opened 2011-02-24 01:55 UTC
hi, i want to ask for your help. I'm applying this patch #7444, and i wonder if it's conflict with your plugin. Let say user A, user B and User C. User A create an issue and assign it to User B, and before user B got the chance to update this issue, user A add notes first. My problem is, whenever this action happen, assignee always change to User C, which is the default assigne for this project, and User C had to assign it back to User B in order the workflow to proceed.

here is the link for the patch http://www.redmine.org/issues/7444

**Comment by ludovic-gasc** [comment] 2011-02-24 14:18
I understand your problem, but the state of this patch is working in progress, the patch will change several times before its hypothetical integration in a stable branch
.
I should fix this bug if the problem is still present with the new version of Redmine or ChiliProject.

Nevertheless, you can send me a patch to fix this problem, I'll integrate in my repository if only your patch works also on a stable branch of Redmine.

Yours.

**Comment by h3ndro** [comment] 2011-03-01 07:25
hi,..you can download the patch from redmine link i already give you,...please give it a try. thx before

**Comment by ludovic-gasc** [comment] 2011-03-01 08:35
Yes, I should review this patch, but I've any interest to do this, I follow only the stable version of Redmine and ChiliProject.
If you really want I work on this, you can pay me to do this work ;-)

**Comment by ludovic-gasc** [comment] 2011-12-20 17:58
I won't fix this bug until this Redmine patch would be included in the official version.

**Closed as completed by ludovic-gasc** 2011-12-20 17:58 UTC
